/*
 * This source file was generated by the Gradle 'init' task
 */
package org.exercise1;

public class App {
    public static void main(String[] args) {
        Singer singer = new Singer();
        System.out.println(singer);

        singer.setId(1);
        singer.setName("Charles Darwin");
        singer.setAddress("Spadina 1");
        singer.setDateOfBirth("01/01/1337");
        singer.setNumberOfAlbums(1337);
        System.out.println(singer);
    }
}
